defaults:
  - dataset: uci_har
  - _self_

common:
  datasets_dir: ../datasets
  resampling_freq: null
  normalization: null # min_max_per_sample
  features_type: channels_only
  include_derivative: false
  sliding_window:
    window_time: 2.56
    overlap: 0
  spectrogram:
    window_size: 20
    overlap: null
    mode: magnitude
