defaults:
  - dataset: uci_har
  - _self_

common:
  datasets_dir: /Users/maxburzer/har-datasets/datasets
  resampling_freq: null
  normalization: null
  features_type: channels_only
  include_derivative: false
  sliding_window:
    window_time: 2.56
    overlap: 0
