info:
  id: uci_har
  url: https://archive.ics.uci.edu/static/public/240/human+activity+recognition+using+smartphones.zip
  sampling_freq: 50

selections:
  activity_names: 
    - WALKING
    - WALKING_UPSTAIRS
    - WALKING_DOWNSTAIRS
    - SITTING
    - STANDING
    - LAYING

  channels: 
    - total_acc_x
    - total_acc_y
    - total_acc_z
    - body_acc_x
    - body_acc_y
    - body_acc_z
    - body_gyro_x
    - body_gyro_y
    - body_gyro_z
    

split:
  split_type: given
  given_split:
    train_subj_ids: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]
    test_subj_ids: [21,22,23,24,25]
    val_subj_ids: [26,27,28,29,30]
  subj_cross_val_split:
    subj_id_group_index: 0
    subj_id_groups:
      - [1, 2, 3]
      - [4, 5, 6]
      - [7, 8, 9]
      - [10, 11, 12]
      - [13, 14, 15]
      - [16, 17, 18]
      - [19, 20, 21]
      - [22, 23, 24]
      - [25, 26, 27]
      - [28, 29, 30]

training:
  batch_size: 32
  shuffle: true
  learning_rate: 0.0001
  num_epochs: 100
