info:
  id: wisdm_12
  url: https://www.cis.fordham.edu/wisdm/includes/datasets/latest/WISDM_ar_latest.tar.gz
  sampling_freq: 20

selections:
  activity_names: 
    - Walking
    - Jogging
    - Upstairs
    - Downstairs
    - Sitting
    - Standing

  channels: 
    - accel_x
    - accel_y
    - accel_z
    

split:
  split_type: given
  given_split:
    train_subj_ids: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13 ,14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]
    test_subj_ids: [ 25, 26, 27, 28, 29, 30]
    val_subj_ids: [31, 32, 33, 34, 35, 36]
  subj_cross_val_split:
    subj_id_group_index: 0
    subj_id_groups:
      - [1, 2, 3, 4, 5, 6]
      - [7, 8, 9, 10, 11, 12]
      - [13, 14, 15, 16, 17, 18]
      - [19, 20, 21, 22, 23, 24]
      - [25, 26, 27, 28, 29, 30]
      - [31, 32, 33, 34, 35, 36]
      
training:
  batch_size: 32
  shuffle: true
  learning_rate: 0.0001
  num_epochs: 100
