file_name: uci_har.csv
dir: /Users/maxburzer/har-datasets/datasets/UCI HAR Dataset
freq_save_path: /Users/maxburzer/har-datasets/datasets/UCI HAR Dataset
used_cols:
  1: "body_acc_x_"
  2: "body_acc_y_"
  3: "body_acc_z_"
  4: "body_gyro_x_"
  5: "body_gyro_y_"
  6: "body_gyro_z_"
  7: "total_acc_x_"
  8: "total_acc_y_"
  9: "total_acc_z_"
label_map:
  1: ["WALKING", true]
  2: ["WALKING_UPSTAIRS", true]
  3: ["WALKING_DOWNSTAIRS", true]
  4: ["SITTING", true]
  5: ["STANDING", true]
  6: ["LAYING", true]
keys:
  all: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30]
  train: [1, 3, 5, 7, 8, 14, 15, 16, 17, 21, 22, 23, 26, 27, 28, 29, 6, 11, 19, 25, 30]
  val: []
  test: [2, 4, 9, 10, 12, 13, 18, 20, 24]
  LOCV:
    - [1, 2, 3]
    - [4, 5, 6]
    - [7, 8, 9]
    - [10, 11, 12]
    - [13, 14, 15]
    - [16, 17, 18]
    - [19, 20, 21]
    - [22, 23, 24]
    - [25, 26, 27]
    - [28, 29, 30]
locv: {}  # not specified in code; keep empty or fill as needed
exp_mode: Given 
split_tag: "sub"
file_encoding: {}
training:
  batch_size: 32
  epochs: 100
  shuffle: true
  drop_last: false
  learning_rate: 0.001
